### ISSUE TITLE
Unzip cause app crash

### ISSUE THREAD

**Issue by expouic** [mockingbot/react-native-zip-archive#116]
On my application the user can download a lot of zip files chunked with max 600 mb after the download when app start to unzip all the files (one by one) the application crash!

> Exception Type:  EXC_CRASH (SIGKILL)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Exception Note:  EXC_CORPSE_NOTIFY
> Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
> Termination Description: SPRINGBOARD, scene-create watchdog transgression: com.myapp.test exhausted real (wall clock) time allowance of 19.31 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 10.120 (user 10.120, system 0.000), 25% CPU", | "Elapsed application CPU time (seconds): 0.498, 1% CPU" | )
> Triggered by Thread:  0

Any ideia to solve this?

**Comment by plrthink** [comment]
According to the error code you provided, I find this so https://stackoverflow.com/questions/18996287/app-crash-in-the-device-exception-0x8badf00d. It says the app was terminated because it takes too long to respond. I would think this is related to the unzipping process, but this module is supposed to run a separate thread. Would have a test on it.
