### ISSUE TITLE
❌  duplicate symbol error, CodePush also installed

### ISSUE THREAD

**Issue by jeffmon** [mockingbot/react-native-zip-archive#150]
# React Native Info
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 377.05 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.3, 27.0.3, 28.0.1, 28.0.3
        System Images: android-17 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
```

# react-native-zip-archive version
`4.1.1`

# Issue

Unable to compile on iOS due to duplicate symbols:

![Screen Shot 2019-07-05 at 4 33 06 PM](https://user-images.githubusercontent.com/18548300/60750323-9819db00-9f42-11e9-86b4-7b3b7ec275b6.png)

We have CodePush installed which might be causing this. Any idea on what to do next?

**Comment by plrthink** [comment]
Yeah, this is because we're both including the ssziparchive into our source code and that would cause the problem. But we still can't find a solution to solve this gently as discussed in 

You can temporarily make it work by the steps mentioned in this comment https://github.com/microsoft/react-native-code-push/issues/241#issuecomment-195639258.

**Comment by plrthink** [comment]
Also would close this issue since we already have an open issue targeting the same problem.

**Comment by pedrosimao** [comment]
@plrthink I can't use the proposes solution because I am using Cocoapods
Can you please provide me with a quick fix?

**Comment by pedrosimao** [comment]
In fact this solution does not work for me. As I can build but when I tried to archive I got this error: `CompileC /Users/pedro1/Library/Developer/Xcode/DerivedData/monspecialisteauto-bwqlznaolophgmemfgpwxzlxwddv/Build/Intermediates.noindex/ArchiveIntermediates/monspecialisteauto/IntermediateBuildFilesPath/CodePush.build/Release-iphoneos/CodePush.build/Objects-normal/armv7/CodePushPackage.o CodePush/CodePushPackage.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler`

**Comment by plrthink** [comment]
@pedrosimao Can you provide more details on your usage? Are you using react-native along with the native code or solely with react-native 60?

**Comment by pedrosimao** [comment]
@plrthink Thanks for your fast support. 
I ended up deleting my Cocoapods and installing the library manually, so I could apply the fix you suggested on CodePush repository some years ago. It ended up working, but it is not ideal because of side effects on every new `npm i`... I am on react-native `0.59.9`. I will just wait for the cocoapods solution and upgrade it.
