### ISSUE TITLE
SSZipArchive as pod dependency

### ISSUE THREAD

**Issue by DomiR** [mockingbot/react-native-zip-archive#151]
Is there a specific reason to why you are not depending on SSZipArchive directly in the podfile? 

I could open a PR similar to https://github.com/SOUNDBOKS/react-native-zip-archive/commit/d2e1ddc8cd0a88f480acb00f9c99e7bd74448313.

Thanks!

**Comment by plrthink** [comment]
The reason is that for users who just using react-native in a 'plain' mode, which is without either expo or existing native iOS app, including the source code is the only way I can find for using the SSZipArchive. But this seems out of date since react-native 60 is enabling the cocoapod by default. So I think we can swap out the ssziparchive source code and let the cocoapod resolve it.

But I think the scope of change is including tweak the cocoapod.spec file, since we have already changed the reference to the right version https://github.com/mockingbot/react-native-zip-archive/blob/master/ios/RNZipArchive.h#L15.

It would be wonderful to open a PR to address this, just remember to ensure it works well with both plain react-native users and the users who embrace the react-native to their existing apps.

**Comment by pedrosimao** [comment]
I would love to see this implemented too. For now I am using the dirty workaround of deleting SSZipArchive from CodePush... I had to delete both libs from my Cocoapods though...

**Comment by pedrosimao** [comment]
Why don't you implement the same solution as here: https://github.com/SOUNDBOKS/react-native-zip-archive/commits/master

**Comment by plrthink** [comment]
@pedrosimao Yeah, I'm working on this these days and actually it works out on my local machine. And I'm still making changes to the Android side to upgrade it with react-native 60. So maybe I can ship it on the next few days.

**Comment by plrthink** [comment]
@pedrosimao @DomiR I have just published the version 5.0.0-alpha.0, which deletes the self-contained SSZipArchive. Please test it out on your use cases to see if it solves the problems. Any feedback towards this change is welcome.

**Comment by DaBs** [comment]
Wonderful to hear that the fix worked! We originally forked and never did a pull request, simply because I wasn't sure if it would work with your intended use-case, but great that it's in there!

**Comment by plrthink** [comment]
Closed since the fixes have been released via [5.0.0](https://github.com/mockingbot/react-native-zip-archive/releases/tag/5.0.0)

**Comment by ospfranco** [comment]
5.0.0 is only compatible with RN 0.60+ right? I cannot update to 0.60 because it breaks compatibility with a bunch of other libraries, is there any other way to make it work on older RN versions?

**Comment by plrthink** [comment]
> 5.0.0 is only compatible with RN 0.60+ right?

Yes.

> is there any other way to make it work on older RN versions?

What's your main purpose in solving SSZipArchive via cocoapod? Old versions of the package use the self-contained copy of SSZipArchive which would work in most scenario, what's the problem are you facing? This would help me to come up with a suitable solution for you.
