### ISSUE TITLE
Wrong folder structure after used zipWithPassword on Android

### ISSUE THREAD

**Issue by kenyuwin** [mockingbot/react-native-zip-archive#161]
When I zip the folder "RootFolder" to "RootFolder.zip" using zipWithPassword, there is a wrong structure in the zip file. If only using zip, there is no problem.

**Before zip:**
RootFolder
---|__Folder
--------|__SubFolder
---------------|__1.txt
---------------|__2.txt

**After zipped:**
RootFolder.zip
---|__Folder
---|-----|__SubFolder
---|-----------|__1.txt
---|-----------|__2.txt
---|__SubFolder
----------|__1.txt
----------|__2.txt

**Comment by plrthink** [comment]
I assume you're running on Android, is this correct?

**Comment by kenyuwin** [comment]
> I assume you're running on Android, is this correct?

Yes

**Comment by kenyuwin** [comment]
For my finding, the reason should be this function in RNZipArchiveModule.java
```
  private List<File> getSubFiles(File baseDir, boolean isContainFolder) {
    List<File> fileList = new ArrayList<>();
    File[] tmpList = baseDir.listFiles();
    for (File file : tmpList) {
      if (file.isFile()) {
        fileList.add(file);
      }
      if (file.isDirectory()) {
        if (isContainFolder) {
          fileList.add(file); //key code
        }
        fileList.addAll(getSubFiles(file, isContainFolder));
      }
    }
    return fileList;
  }
```

This code added additional folders into the zip file.
`fileList.addAll(getSubFiles(file, isContainFolder));`

**Comment by plrthink** [comment]
Yeap, the reason is they use different implementation under the hood. The `zip` method is using a homebrewed version which needs to include all its subfiles and folders, while `zipWithPassword` utilizes the [zip4j](https://github.com/srikanth-lingala/zip4j) which doesn't need that shape of data.

It would be great if you can open a PR to fix this by making use of zip4j behind the `zip` method as `zipWithPassword` does. And I could do the review to help this fix getting released.
