### ISSUE TITLE
Is it possible to unzip into a string (rather than a file)?

### ISSUE THREAD

**Issue by acb** [mockingbot/react-native-zip-archive#176]
I'm looking into bundling a significant dataset into my app and want to compress it so it doesn't inflate my app size too much.

Is it possible to use this lib to unzip a file directly into a string, rather than having it output to a file in the filesystem?  It would be great to be able to just unzip some data into a component so I can reference it rather than unzip to a file, read that in, and then try and make sure to delete it when I'm done which can lead to file system leaks if the user unmounts the component/closes the app while all this is happening.

**Comment by plrthink** [comment]
I'm afraid of we can't do this since all the implementation details are targeting the file system. If your concern is all about not deleting the uncompleted downloads when the user wants to cancel that, maybe we can do something to clean it up at the appropriate time. And that would be a great feature.
