### ISSUE TITLE
Add support for application/gzip files

### ISSUE THREAD

**Issue by betoharres** [mockingbot/react-native-zip-archive#181]
Hello, thanks for creating this library! =]
On Android, I'm not able to extract `.gz` files, I'm getting this error:
```
Error: Failed to extract file error in opening zip file
```

 I've made a sample project showing my problem:
https://github.com/betoharres/rn-zip-archive-problem
Just press the button "PRESS ME".

I'm a big noob on Java and Obj-C, but I'm happy to try to help.
I'm already looking into `RNZipArchiveModule.java` but I have no clue of what to do :(
 
Let me know if I can help with anything, because this is blocking me on the project I'm currently working on.
Thanks :heart:

**Comment by betoharres** [comment]
Turns out the problem is here:
https://github.com/mockingbot/react-native-zip-archive/blob/master/android/src/main/java/com/rnziparchive/RNZipArchiveModule.java#L30 

Because the library is using this package that does not support gzip files, and `.zip` and `.gz` files are different as stated here:
https://stackoverflow.com/questions/13644538/why-zipfilefile-zipfile-open-read-does-not-work-for-gzip

And doing a quick google search I found a *probably* good example on how to implement this
https://stackoverflow.com/questions/13644538/why-zipfilefile-zipfile-open-read-does-not-work-for-gzip

But, like I said, I'm a total noob on this area, so that last link might be wrong.
Anyway, I hope those links flash some light into the problem and some response from anyone here with an ideia on how to solve this;

thanks

**Comment by plrthink** [comment]
Thanks for giving so much effort to this project. Thanks!

And yes, we're not supporting gzip format, which is inherited from the underlying libraries(SSZipArchive on iOS and  Zip4j on Android). And also in my personal opinion, it would be better if the project only targets the zip format because the 'do one thing, and do it well'.

For the issue you're facing, I'm afraid that you should find the other library to handle the gzip format like `react-native-gzip`.

**Comment by betoharres** [comment]
Hi @plrthink ! thanks for reaching out quickly! :) I totally understand you; I'll check those options.

thanks for the recommendation.
