### ISSUE TITLE
Unable to unzip

### ISSUE THREAD

**Issue by kulikalov** [mockingbot/react-native-zip-archive#201]
I've tried creating archives with `zip`, `gzip` and mac's `compress` commands. With or without passwords. This library was unable to unzip any of them. Judging by a bunch of issues in this repo, I have to zip it differently. What app/script/cli should I use??

**Comment by plrthink** [comment]
Which platform you are trying to unzip? Andriod or iOS? And can you provide a minimal repo to produce this?

**Comment by kulikalov** [comment]
ios. Could you just give me a correctly zipped archive to test if my assumption is correct?

**Comment by plrthink** [comment]
Sure, you can test with this https://rnza-test-app-assets.firebaseapp.com/static_password.zip file and its password is 'helloworld'. Also you can see the example app https://github.com/plrthink/RNZATestApp for prototyping.

**Comment by danilo900** [comment]
Hello Iam having trouble here either!
IAm getting always "crc check failed for file"

I just did a simple zip on my Mac and I haved tryed to unzip.

No success! :/

"react-native-zip-archive": "^5.0.3"

**Comment by danilo900** [comment]
> Sure, you can test with this https://rnza-test-app-assets.firebaseapp.com/static_password.zip file and its password is 'helloworld'. Also you can see the example app https://github.com/plrthink/RNZATestApp for prototyping.

Man, its so weird! hahahaah ....

I have tried with that static_password.

Well, its a little best, because it not give an error. 
(log below from subscribe on unzip)
<img width="226" alt="Screen Shot 2020-07-07 at 10 49 01" src="https://user-images.githubusercontent.com/33874563/86791041-7cf31700-c03f-11ea-93bc-22ac1f113512.png">

BUT .... 

NOTHING are unzipped on the destination folder.... 
![Screen Shot 2020-07-07 at 10 50 07](https://user-images.githubusercontent.com/33874563/86791174-a318b700-c03f-11ea-80ed-7cc48c9c1cd8.png)

**Comment by danilo900** [comment]
Hello @plrthink I just did a PR solving it!

It really simple, just adding normalizeFilePath to the target!

Can you approve it? https://github.com/mockingbot/react-native-zip-archive/pull/208

Thanks!

**Comment by kimivn** [comment]
i have same issue , i zip my file to 4,3GB then module die
